---
- name: Unzip the frontend file
  unarchive:
    src: "frontend.zip"
    dest: "~/"
    creates: "~/front/package.json"
  register: unarchive

- name: Copy environment files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
  - { src: "environment.ts.j2", dest: "~/front/src/environments/environment.ts" }
  - { src: "environment.prod.ts.j2", dest: "~/front/src/environments/environment.prod.ts" }

- name: Install node packages with Yarn
  yarn:
    path: "~/front"
    state: present
  changed_when: "unarchive.changed == true"

- name: Copy frontend service file LAUNCH SERVICE
  copy:
    src: "frontend.service"
    dest: "/lib/systemd/system/frontend.service"


