---

- name: Install util packages
  apt:
    pkg: unzip, zip, wget, curl, software-properties-common, build-essential

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x buster main"
    state: present
    update_cache: yes

- name: Install NodeJS et npm
  apt:
    pkg: nodejs
    state: present
    update_cache: yes

- name: Install Angular.js
  npm:
    name: "@angular/cli"
    global: yes
    state: present

- name: Install Yarn
  npm:
    name: "yarn"
    global: yes
    state: present