- name: Install and initialize MySQL database server
  hosts: bdd
  roles:
    - role: mysql
      become: yes

- name: Launch Laravel with php for backend app
  hosts: backend
  roles:
    - role: backend
      become: yes